# Fact Table
This workbook is just use to read all the CSV files contained in Resources20-21 (containing the last 6 months of published data) and merge them in one big table that I am going to use within Tableau.

In [1]:
import pandas as pd
import os
import fnmatch

In [2]:
os.chdir('./Resources20-21/')

In [3]:
data =[]
for file in os.listdir('./'):
    if fnmatch.fnmatch(file, '*.csv'):
        data += [pd.read_csv(file)] 
df = pd.concat(data, join='outer', axis=0)
df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1062,2020-06-01 00:00:03.3720,2020-06-01 00:17:46.2080,3419,Douglass St & 4 Ave,40.679279,-73.981540,3419,Douglass St & 4 Ave,40.679279,-73.981540,39852,Customer,1997,2
1,3810,2020-06-01 00:00:03.5530,2020-06-01 01:03:33.9360,366,Clinton Ave & Myrtle Ave,40.693261,-73.968896,336,Sullivan St & Washington Sq,40.730477,-73.999061,37558,Subscriber,1969,0
2,1017,2020-06-01 00:00:09.6140,2020-06-01 00:17:06.8330,389,Broadway & Berry St,40.710446,-73.965251,3562,Classon Ave & St Marks Ave,40.676520,-73.959608,37512,Customer,1988,2
3,226,2020-06-01 00:00:12.1780,2020-06-01 00:03:58.8640,3255,8 Ave & W 31 St,40.750585,-73.994685,505,6 Ave & W 33 St,40.749013,-73.988484,39674,Customer,1969,0
4,1437,2020-06-01 00:00:21.2550,2020-06-01 00:24:18.9650,367,E 53 St & Lexington Ave,40.758281,-73.970694,497,E 17 St & Broadway,40.737050,-73.990093,21093,Customer,1997,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
634626,135,2021-02-28 23:57:55.5560,2021-03-01 00:00:10.8970,3555,28 St & 41 Ave,40.751047,-73.937970,3129,Queens Plaza North & Crescent St,40.751102,-73.940737,47853,Subscriber,1988,1
634627,358,2021-02-28 23:58:44.3410,2021-03-01 00:04:42.9870,526,E 33 St & 5 Ave,40.747659,-73.984907,540,Lexington Ave & E 29 St,40.743116,-73.982154,45496,Customer,1969,0
634628,289,2021-02-28 23:59:12.6970,2021-03-01 00:04:02.4910,519,Pershing Square North,40.751873,-73.977706,367,E 53 St & Lexington Ave,40.758281,-73.970694,41038,Customer,1969,0
634629,166,2021-02-28 23:59:17.8860,2021-03-01 00:02:04.4920,3134,3 Ave & E 62 St,40.763126,-73.965269,3141,1 Ave & E 68 St,40.765005,-73.958185,37383,Subscriber,1986,1
634630,236,2021-02-28 23:59:26.8890,2021-03-01 00:03:23.2470,3516,31 St & Astoria Blvd,40.769918,-73.918406,3593,31 St & Broadway,40.761584,-73.925921,48632,Customer,1969,0

In [4]:
#check if there is any NA value
df.isna().sum()

tripduration               0
starttime                  0
stoptime                   0
start station id           0
start station name         0
start station latitude     0
start station longitude    0
end station id             0
end station name           0
end station latitude       0
end station longitude      0
bikeid                     0
usertype                   0
birth year                 0
gender                     0
dtype: int64

In [5]:
# checking for wrong values
df['birth year'].unique()

array([1997, 1969, 1988, 1990, 1938, 1995, 1971, 1989, 1984, 1996, 1975,
       1982, 1994, 1973, 2000, 1951, 1985, 1977, 1986, 1993, 1992, 1968,
       1967, 2003, 1970, 1980, 1964, 2001, 1979, 1987, 1965, 1999, 1962,
       1981, 1955, 1998, 1976, 1991, 2002, 1978, 1983, 1958, 1972, 1961,
       1960, 1953, 1966, 1957, 1974, 1956, 1959, 1963, 1954, 1941, 1948,
       1946, 1950, 1900, 1949, 1947, 1945, 1952, 1930, 1940, 1943, 1939,
       1933, 2004, 1944, 1934, 1942, 1937, 1887, 1932, 1935, 1893, 1891,
       1890, 1931, 1873, 1897, 1918, 1885, 1912, 1928, 1896, 1922, 1936,
       1917, 1901, 1923, 1888, 1907, 1909, 1916, 1886, 1905, 1889, 1898,
       1911, 1920, 1919, 1899, 1884, 1910, 1915, 1879, 1913, 1895, 1892,
       1929, 1921, 1924, 1927, 1902, 1925, 1894, 1866, 2005, 1926, 1914])

In [6]:
#if the birth year is lower than 1940 the customer/subscribes is more than 79 years old in 2019.
# I am assuming those are wrong entries and as a consequence I am dropping those rows.
df = df[df['birth year'] >= 1940]
df['birth year'].unique()

array([1997, 1969, 1988, 1990, 1995, 1971, 1989, 1984, 1996, 1975, 1982,
       1994, 1973, 2000, 1951, 1985, 1977, 1986, 1993, 1992, 1968, 1967,
       2003, 1970, 1980, 1964, 2001, 1979, 1987, 1965, 1999, 1962, 1981,
       1955, 1998, 1976, 1991, 2002, 1978, 1983, 1958, 1972, 1961, 1960,
       1953, 1966, 1957, 1974, 1956, 1959, 1963, 1954, 1941, 1948, 1946,
       1950, 1949, 1947, 1945, 1952, 1940, 1943, 2004, 1944, 1942, 2005])

In [7]:
#I am dropping the rows of people with unknown gender, just because I need to trim the dataset under 15M rows to handle it with Tableau Public
df = df[df['gender'] != 0]
df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1062,2020-06-01 00:00:03.3720,2020-06-01 00:17:46.2080,3419,Douglass St & 4 Ave,40.679279,-73.981540,3419,Douglass St & 4 Ave,40.679279,-73.981540,39852,Customer,1997,2
2,1017,2020-06-01 00:00:09.6140,2020-06-01 00:17:06.8330,389,Broadway & Berry St,40.710446,-73.965251,3562,Classon Ave & St Marks Ave,40.676520,-73.959608,37512,Customer,1988,2
4,1437,2020-06-01 00:00:21.2550,2020-06-01 00:24:18.9650,367,E 53 St & Lexington Ave,40.758281,-73.970694,497,E 17 St & Broadway,40.737050,-73.990093,21093,Customer,1997,2
5,355,2020-06-01 00:00:22.6500,2020-06-01 00:06:18.5250,248,Laight St & Hudson St,40.721854,-74.007718,247,Perry St & Bleecker St,40.735354,-74.004831,39594,Subscriber,1990,1
7,1810,2020-06-01 00:00:27.5880,2020-06-01 00:30:38.2560,3263,Cooper Square & Astor Pl,40.729515,-73.990753,496,E 16 St & 5 Ave,40.737262,-73.992390,16571,Customer,1995,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
634607,192,2021-02-28 23:51:54.1600,2021-02-28 23:55:06.4950,303,Mercer St & Spring St,40.723627,-73.999496,257,Lispenard St & Broadway,40.719392,-74.002472,14939,Subscriber,1968,1
634613,222,2021-02-28 23:52:36.8360,2021-02-28 23:56:19.2790,4283,38 St & 30 Ave,40.764175,-73.915840,3595,35 St & Broadway,40.760339,-73.922243,47713,Subscriber,1991,1
634617,323,2021-02-28 23:53:45.0160,2021-02-28 23:59:08.8370,3052,Lewis Ave & Madison St,40.686312,-73.935775,437,Macon St & Nostrand Ave,40.680983,-73.950048,44705,Subscriber,1992,1
634626,135,2021-02-28 23:57:55.5560,2021-03-01 00:00:10.8970,3555,28 St & 41 Ave,40.751047,-73.937970,3129,Queens Plaza North & Crescent St,40.751102,-73.940737,47853,Subscriber,1988,1
634629,166,2021-02-28 23:59:17.8860,2021-03-01 00:02:04.4920,3134,3 Ave & E 62 St,40.763126,-73.965269,3141,1 Ave & E 68 St,40.765005,-73.958185,37383,Subscriber,1986,1

In [8]:
#replacing the numerical number for sex with characters
df["gender"].replace({1: "male", 2: "female"}, inplace=True)
df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1062,2020-06-01 00:00:03.3720,2020-06-01 00:17:46.2080,3419,Douglass St & 4 Ave,40.679279,-73.981540,3419,Douglass St & 4 Ave,40.679279,-73.981540,39852,Customer,1997,female
2,1017,2020-06-01 00:00:09.6140,2020-06-01 00:17:06.8330,389,Broadway & Berry St,40.710446,-73.965251,3562,Classon Ave & St Marks Ave,40.676520,-73.959608,37512,Customer,1988,female
4,1437,2020-06-01 00:00:21.2550,2020-06-01 00:24:18.9650,367,E 53 St & Lexington Ave,40.758281,-73.970694,497,E 17 St & Broadway,40.737050,-73.990093,21093,Customer,1997,female
5,355,2020-06-01 00:00:22.6500,2020-06-01 00:06:18.5250,248,Laight St & Hudson St,40.721854,-74.007718,247,Perry St & Bleecker St,40.735354,-74.004831,39594,Subscriber,1990,male
7,1810,2020-06-01 00:00:27.5880,2020-06-01 00:30:38.2560,3263,Cooper Square & Astor Pl,40.729515,-73.990753,496,E 16 St & 5 Ave,40.737262,-73.992390,16571,Customer,1995,female
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
634607,192,2021-02-28 23:51:54.1600,2021-02-28 23:55:06.4950,303,Mercer St & Spring St,40.723627,-73.999496,257,Lispenard St & Broadway,40.719392,-74.002472,14939,Subscriber,1968,male
634613,222,2021-02-28 23:52:36.8360,2021-02-28 23:56:19.2790,4283,38 St & 30 Ave,40.764175,-73.915840,3595,35 St & Broadway,40.760339,-73.922243,47713,Subscriber,1991,male
634617,323,2021-02-28 23:53:45.0160,2021-02-28 23:59:08.8370,3052,Lewis Ave & Madison St,40.686312,-73.935775,437,Macon St & Nostrand Ave,40.680983,-73.950048,44705,Subscriber,1992,male
634626,135,2021-02-28 23:57:55.5560,2021-03-01 00:00:10.8970,3555,28 St & 41 Ave,40.751047,-73.937970,3129,Queens Plaza North & Crescent St,40.751102,-73.940737,47853,Subscriber,1988,male
634629,166,2021-02-28 23:59:17.8860,2021-03-01 00:02:04.4920,3134,3 Ave & E 62 St,40.763126,-73.965269,3141,1 Ave & E 68 St,40.765005,-73.958185,37383,Subscriber,1986,male

In [9]:
# I am converting the trip time in minutes instead of seconds
df['tripduration']=df['tripduration'].divide(60)
df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,17.700000,2020-06-01 00:00:03.3720,2020-06-01 00:17:46.2080,3419,Douglass St & 4 Ave,40.679279,-73.981540,3419,Douglass St & 4 Ave,40.679279,-73.981540,39852,Customer,1997,female
2,16.950000,2020-06-01 00:00:09.6140,2020-06-01 00:17:06.8330,389,Broadway & Berry St,40.710446,-73.965251,3562,Classon Ave & St Marks Ave,40.676520,-73.959608,37512,Customer,1988,female
4,23.950000,2020-06-01 00:00:21.2550,2020-06-01 00:24:18.9650,367,E 53 St & Lexington Ave,40.758281,-73.970694,497,E 17 St & Broadway,40.737050,-73.990093,21093,Customer,1997,female
5,5.916667,2020-06-01 00:00:22.6500,2020-06-01 00:06:18.5250,248,Laight St & Hudson St,40.721854,-74.007718,247,Perry St & Bleecker St,40.735354,-74.004831,39594,Subscriber,1990,male
7,30.166667,2020-06-01 00:00:27.5880,2020-06-01 00:30:38.2560,3263,Cooper Square & Astor Pl,40.729515,-73.990753,496,E 16 St & 5 Ave,40.737262,-73.992390,16571,Customer,1995,female
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
634607,3.200000,2021-02-28 23:51:54.1600,2021-02-28 23:55:06.4950,303,Mercer St & Spring St,40.723627,-73.999496,257,Lispenard St & Broadway,40.719392,-74.002472,14939,Subscriber,1968,male
634613,3.700000,2021-02-28 23:52:36.8360,2021-02-28 23:56:19.2790,4283,38 St & 30 Ave,40.764175,-73.915840,3595,35 St & Broadway,40.760339,-73.922243,47713,Subscriber,1991,male
634617,5.383333,2021-02-28 23:53:45.0160,2021-02-28 23:59:08.8370,3052,Lewis Ave & Madison St,40.686312,-73.935775,437,Macon St & Nostrand Ave,40.680983,-73.950048,44705,Subscriber,1992,male
634626,2.250000,2021-02-28 23:57:55.5560,2021-03-01 00:00:10.8970,3555,28 St & 41 Ave,40.751047,-73.937970,3129,Queens Plaza North & Crescent St,40.751102,-73.940737,47853,Subscriber,1988,male
634629,2.766667,2021-02-28 23:59:17.8860,2021-03-01 00:02:04.4920,3134,3 Ave & E 62 St,40.763126,-73.965269,3141,1 Ave & E 68 St,40.765005,-73.958185,37383,Subscriber,1986,male

In [10]:
os.chdir('./../')

In [11]:
df.to_csv('CityBike.csv')